# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoCoding.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VideoCoding(object):
    def setupUi(self, VideoCoding):
        VideoCoding.setObjectName("VideoCoding")
        VideoCoding.resize(420, 500)
        font = QtGui.QFont()
        font.setPointSize(4)
        VideoCoding.setFont(font)
        VideoCoding.setWindowOpacity(8.0)
        self.centralwidget = QtWidgets.QWidget(VideoCoding)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setGeometry(QtCore.QRect(240, 30, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setGeometry(QtCore.QRect(240, 80, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.lineEdit_ID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ID.setGeometry(QtCore.QRect(80, 30, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_ID.setFont(font)
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 37, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 140, 291, 20))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 87, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_Trial = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Trial.setGeometry(QtCore.QRect(80, 80, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_Trial.setFont(font)
        self.lineEdit_Trial.setObjectName("lineEdit_Trial")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 180, 360, 290))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        VideoCoding.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VideoCoding)
        self.statusbar.setObjectName("statusbar")
        VideoCoding.setStatusBar(self.statusbar)

        self.retranslateUi(VideoCoding)
        QtCore.QMetaObject.connectSlotsByName(VideoCoding)
        VideoCoding.setTabOrder(self.lineEdit_ID, self.pushButton_Start)
        VideoCoding.setTabOrder(self.pushButton_Start, self.pushButton_Stop)

    def retranslateUi(self, VideoCoding):
        _translate = QtCore.QCoreApplication.translate
        VideoCoding.setWindowTitle(_translate("VideoCoding", "MainWindow"))
        self.pushButton_Start.setText(_translate("VideoCoding", "Start"))
        self.pushButton_Stop.setText(_translate("VideoCoding", "Stop"))
        self.label.setText(_translate("VideoCoding", "ID"))
        self.label_2.setText(_translate("VideoCoding", "Coding : Keep Hold down  [ Ctrl ]  key"))
        self.label_3.setText(_translate("VideoCoding", "Trial"))

