# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoCoding.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VideoCoding(object):
    def setupUi(self, VideoCoding):
        VideoCoding.setObjectName("VideoCoding")
        VideoCoding.resize(420, 500)
        font = QtGui.QFont()
        font.setPointSize(4)
        font.setStrikeOut(False)
        VideoCoding.setFont(font)
        VideoCoding.setWindowOpacity(8.0)
        self.centralwidget = QtWidgets.QWidget(VideoCoding)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setGeometry(QtCore.QRect(240, 30, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setGeometry(QtCore.QRect(240, 80, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.lineEdit_ID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ID.setGeometry(QtCore.QRect(80, 30, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_ID.setFont(font)
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.label_ID = QtWidgets.QLabel(self.centralwidget)
        self.label_ID.setGeometry(QtCore.QRect(30, 37, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_ID.setFont(font)
        self.label_ID.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ID.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID.setObjectName("label_ID")
        self.label_Explain = QtWidgets.QLabel(self.centralwidget)
        self.label_Explain.setGeometry(QtCore.QRect(20, 140, 281, 20))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(11)
        self.label_Explain.setFont(font)
        self.label_Explain.setObjectName("label_Explain")
        self.label_Trial = QtWidgets.QLabel(self.centralwidget)
        self.label_Trial.setGeometry(QtCore.QRect(20, 87, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_Trial.setFont(font)
        self.label_Trial.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Trial.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Trial.setObjectName("label_Trial")
        self.lineEdit_Trial = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Trial.setGeometry(QtCore.QRect(80, 80, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_Trial.setFont(font)
        self.lineEdit_Trial.setObjectName("lineEdit_Trial")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(19, 180, 381, 290))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_Now = QtWidgets.QLabel(self.centralwidget)
        self.label_Now.setGeometry(QtCore.QRect(310, 140, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_Now.setFont(font)
        self.label_Now.setStyleSheet("QLabel {  color : rgb(255, 170, 0); }")
        self.label_Now.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Now.setObjectName("label_Now")
        VideoCoding.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VideoCoding)
        self.statusbar.setObjectName("statusbar")
        VideoCoding.setStatusBar(self.statusbar)

        self.retranslateUi(VideoCoding)
        QtCore.QMetaObject.connectSlotsByName(VideoCoding)
        VideoCoding.setTabOrder(self.lineEdit_ID, self.pushButton_Start)
        VideoCoding.setTabOrder(self.pushButton_Start, self.pushButton_Stop)

    def retranslateUi(self, VideoCoding):
        _translate = QtCore.QCoreApplication.translate
        VideoCoding.setWindowTitle(_translate("VideoCoding", "MainWindow"))
        self.pushButton_Start.setText(_translate("VideoCoding", "Start"))
        self.pushButton_Stop.setText(_translate("VideoCoding", "Stop"))
        self.label_ID.setText(_translate("VideoCoding", "ID"))
        self.label_Explain.setText(_translate("VideoCoding", "Coding : Keep Hold down [ Ctrl ] key"))
        self.label_Trial.setText(_translate("VideoCoding", "Trial"))
        self.label_Now.setText(_translate("VideoCoding", "Release"))

